### ISSUE TITLE
The maintenance of the web-ui code base

### ISSUE THREAD

**Issue by fno2010** [cmscaltech/web-ui#1]
It seems that there are multiple upstream repos maintaining this code base. And the original code base (https://github.com/kytos/web-ui) has been removed.

Are we going to use this repo as the upstream repo? If so, the current problem is that other existing forks cannot send any pull requests to this repo now. Because their upstream is not pointing to this one.

**Comment by juztas** [comment]
You will have to re-fork and merge old code base with this forked version. Please also after that create pull request. Thanks
